#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jul 01 00:18:21 MSK 2026
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto d0e531f711b941e0817f03148931c572 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot lab_15_tb_bluster_behav xil_defaultlib.lab_15_tb_bluster xil_defaultlib.glbl -log elaborate.log"
xelab -wto d0e531f711b941e0817f03148931c572 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot lab_15_tb_bluster_behav xil_defaultlib.lab_15_tb_bluster xil_defaultlib.glbl -log elaborate.log

